In [2]:
print("hello, lets begin numpy with Array foundamentals")


hello, lets begin numpy with Array foundamentals


In [47]:
import numpy as np


Creating arrays from lists or functions

Understanding shape, dtype, ndim

Array attributes (size, itemsize)

Reshape, flatten, transpose

Type conversion (astype)

Element-wise operations (add, sub, mul, div)

arange, linspace, zeros, ones, full, eye



In [5]:
myarray = np.random.choice([1, 2, 3, 4, 5])

In [6]:
myarray


np.int64(2)

In [7]:
a=[1,2,3,4,5,6,7,8,9,10]


In [8]:
type(a)

list

In [9]:
x=np.array(a)

In [11]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(x)

numpy.ndarray

In [14]:
c=np.array([a,x])

In [15]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [9]:
c=np.array([1,2,3,4],dtype=np.float32)

In [18]:
c

array([1., 2., 3., 4.], dtype=float32)

Arrays of zero and ones

In [19]:
x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

Random numbers in ndarrays 

In [13]:
random_array=np.random.rand(2,5)

In [14]:

random_array


array([[0.02765807, 0.17968611, 0.14296706, 0.4856639 , 0.22623404],
       [0.70976896, 0.56709314, 0.35393227, 0.92720295, 0.10826666]])

In [15]:
print(random_array)

[[0.02765807 0.17968611 0.14296706 0.4856639  0.22623404]
 [0.70976896 0.56709314 0.35393227 0.92720295 0.10826666]]


In [16]:
p=np.random.randint(1,100, size=(4,4))

In [17]:
p

array([[61, 62, 37, 82],
       [64, 84, 17, 63],
       [64, 22,  3, 26],
       [95, 28, 41, 19]], dtype=int32)

In [18]:
print(p)

[[61 62 37 82]
 [64 84 17 63]
 [64 22  3 26]
 [95 28 41 19]]


In [19]:
np.random.randn(2,3)

array([[-1.0998605 , -1.67517283, -0.44095551],
       [-0.20586903, -1.09402998,  0.19980285]])

In [20]:
np.random.choice([1,2,3,4,5], size=(2,3))

array([[4, 3, 4],
       [5, 4, 4]])

An array of your choice lets play

In [21]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [22]:
np.full((3,5),10,dtype=np.int32)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int32)

In [23]:
np.ones((4,4))*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

Identity matrix

In [43]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
identity_matrix = np.eye(4,dtype=np.int32)
identity_matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

Evenly spaced ndarray

In [77]:
e=np.arange(5,11)
print(e)



[ 5  6  7  8  9 10]


In [52]:
type(e)

numpy.ndarray

In [53]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [58]:
np.linspace(0,3,5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

Dimension of nparray

In [60]:
a=[10,20,30,40,50]
p=np.array(a)
print(p)

[10 20 30 40 50]


In [61]:
p.ndim

1

In [66]:
b=[1,2,3,4,5]
q=np.array([p,b])
print(q)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [67]:
q.ndim

2

In [68]:
q.shape

(2, 5)

In [69]:
q.size

10

In [74]:
a=np.array([3,4,6,7])

In [75]:
np.reshape(a,(2,2))

array([[3, 4],
       [6, 7]])

In [76]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])