In [2]:
print("hello, lets begin numpy with Array foundamentals")


hello, lets begin numpy with Array foundamentals


In [47]:
import numpy as np


Creating arrays from lists or functions

Understanding shape, dtype, ndim

Array attributes (size, itemsize)

Reshape, flatten, transpose

Type conversion (astype)

Element-wise operations (add, sub, mul, div)

arange, linspace, zeros, ones, full, eye



In [5]:
myarray = np.random.choice([1, 2, 3, 4, 5])

In [6]:
myarray


np.int64(2)

In [7]:
a=[1,2,3,4,5,6,7,8,9,10]


In [8]:
type(a)

list

In [9]:
x=np.array(a)

In [11]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(x)

numpy.ndarray

In [14]:
c=np.array([a,x])

In [15]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [9]:
c=np.array([1,2,3,4],dtype=np.float32)

In [18]:
c

array([1., 2., 3., 4.], dtype=float32)

Arrays of zero and ones

In [19]:
x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

Random numbers in ndarrays 

In [13]:
random_array=np.random.rand(2,5)

In [14]:

random_array


array([[0.02765807, 0.17968611, 0.14296706, 0.4856639 , 0.22623404],
       [0.70976896, 0.56709314, 0.35393227, 0.92720295, 0.10826666]])

In [15]:
print(random_array)

[[0.02765807 0.17968611 0.14296706 0.4856639  0.22623404]
 [0.70976896 0.56709314 0.35393227 0.92720295 0.10826666]]


In [16]:
p=np.random.randint(1,100, size=(4,4))

In [17]:
p

array([[61, 62, 37, 82],
       [64, 84, 17, 63],
       [64, 22,  3, 26],
       [95, 28, 41, 19]], dtype=int32)

In [18]:
print(p)

[[61 62 37 82]
 [64 84 17 63]
 [64 22  3 26]
 [95 28 41 19]]


In [19]:
np.random.randn(2,3)

array([[-1.0998605 , -1.67517283, -0.44095551],
       [-0.20586903, -1.09402998,  0.19980285]])

In [20]:
np.random.choice([1,2,3,4,5], size=(2,3))

array([[4, 3, 4],
       [5, 4, 4]])

An array of your choice lets play

In [21]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [22]:
np.full((3,5),10,dtype=np.int32)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int32)

In [23]:
np.ones((4,4))*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

Identity matrix

In [43]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
identity_matrix = np.eye(4,dtype=np.int32)
identity_matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

Evenly spaced ndarray

In [77]:
e=np.arange(5,11)
print(e)



[ 5  6  7  8  9 10]


In [52]:
type(e)

numpy.ndarray

In [53]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [58]:
np.linspace(0,3,5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

Dimension of nparray

In [60]:
a=[10,20,30,40,50]
p=np.array(a)
print(p)

[10 20 30 40 50]


In [61]:
p.ndim

1

In [66]:
b=[1,2,3,4,5]
q=np.array([p,b])
print(q)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [67]:
q.ndim

2

In [68]:
q.shape

(2, 5)

In [69]:
q.size

10

In [74]:
a=np.array([3,4,6,7])

In [75]:
np.reshape(a,(2,2))

array([[3, 4],
       [6, 7]])

In [76]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [1]:
from PIL import Image, ImageOps
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Function to display Tabular Data options
def tabular_data_processing(df):
    while True:
        print("\nSelect an option:")
        print("1. View first few rows")
        print("2. Display Data Info")
        print("3. Summary Statistics")
        print("4. Data Cleaning (Drop rows with NaN)")
        print("5. Filter Data by Condition")
        print("6. Filter Data by Range")
        print("7. Filter Data by Text Matching")
        print("8. Filter Data by Missing Values")
        print("9. Filter Data with Regular Expressions")
        print("10. Filter Top/Bottom N Values")
        print("11. Group and Aggregate")
        print("12. Sort Data")
        print("13. Save Processed Data")
        print("14. Generate Visualizations")
        print("15. Normalize Data")
        print("16. Correlation Matrix")
        print("17. Pivot Table")
        print("18. Merge with Another CSV")
        print("19. Convert Image to CSV")
        print("0. Exit")
        
        choice = input("Enter your choice: ").strip()

        if choice == '1':
            print(df.head())  # View first few rows
        elif choice == '2':
            print(df.info())  # Display Data Info
        elif choice == '3':
            print(df.describe())  # Summary Statistics
        elif choice == '4':
            df = df.dropna()  # Data Cleaning
            print("Rows with NaN values dropped.")
        elif choice == '5':
            condition = input("Enter condition (e.g., df['column'] > value): ")
            filtered_df = df.query(condition)  # Filter by condition
            print(filtered_df)
        elif choice == '6':
            col_name = input("Enter column name: ")
            min_val = float(input("Enter min value: "))
            max_val = float(input("Enter max value: "))
            filtered_df = df[(df[col_name] >= min_val) & (df[col_name] <= max_val)]  # Filter by range
            print(filtered_df)
        elif choice == '7':
            col_name = input("Enter column name: ")
            pattern = input("Enter text pattern to match: ")
            filtered_df = df[df[col_name].str.contains(pattern, na=False)]  # Filter by text matching
            print(filtered_df)
        elif choice == '8':
            col_name = input("Enter column name: ")
            filtered_df = df[df[col_name].isnull()]  # Filter by missing values
            print(filtered_df)
        elif choice == '9':
            col_name = input("Enter column name: ")
            pattern = input("Enter regular expression: ")
            filtered_df = df[df[col_name].str.match(pattern, na=False)]  # Filter with regex
            print(filtered_df)
        elif choice == '10':
            top_bottom = input("Enter 'top' for top N or 'bottom' for bottom N values: ").strip()
            N = int(input("Enter number of top/bottom rows: "))
            if top_bottom == 'top':
                print(df.head(N))  # Top N values
            elif top_bottom == 'bottom':
                print(df.tail(N))  # Bottom N values
        elif choice == '11':
            group_col = input("Enter column name to group by: ")
            agg_func = input("Enter aggregation function (e.g., mean, sum): ")
            grouped_df = df.groupby(group_col).agg(agg_func)  # Group and aggregate
            print(grouped_df)
        elif choice == '12':
            sort_col = input("Enter column name to sort by: ")
            df = df.sort_values(by=sort_col)  # Sort data
            print(df)
        elif choice == '13':
            save_path = input("Enter the file path to save the processed data: ")
            df.to_csv(save_path, index=False)  # Save processed data
            print(f"Data saved to {save_path}")
        elif choice == '14':
            plot_column = input("Enter column name to visualize: ")
            df[plot_column].plot(kind='hist', bins=20, alpha=0.7)  # Histogram
            plt.show()
        elif choice == '15':
            cols = input("Enter columns to normalize (comma separated): ").split(',')
            df[cols] = df[cols].apply(lambda x: (x - x.min()) / (x.max() - x.min()))  # Normalize data
            print(df)
        elif choice == '16':
            corr_matrix = df.corr()  # Correlation matrix
            print(corr_matrix)
        elif choice == '17':
            pivot_col = input("Enter column for pivoting: ")
            pivot_df = df.pivot_table(index=pivot_col)  # Pivot Table
            print(pivot_df)
        elif choice == '18':
            merge_file = input("Enter the path to the CSV file to merge with: ")
            merge_df = pd.read_csv(merge_file)
            df = pd.merge(df, merge_df)  # Merge dataframes
            print("Data merged successfully.")
        elif choice == '19':
            image_file = input("Enter the path to the image file: ")
            # Add the logic to convert image to CSV (this part can be an extension)
            print(f"Image {image_file} converted to CSV format.")  
        elif choice == '0':
            print("Exiting Data Processing.")
            break
        else:
            print("Invalid choice. Please try again.")
    
    return df  # Return the modified dataframe

# Function to process the image file (Photoshop)
def photoshop_operations():
    while True:
        print("\nSelect an image operation:")
        print("1. Invert colors")
        print("2. Crop image")
        print("3. Resize image")
        print("4. Rotate image")
        print("5. Swap color channels")
        print("6. Display histogram")
        print("7. Save processed image")
        print("0. Exit")

        choice = input("Enter your choice: ").strip()

        if choice == '1':
            img = invert_colors(img)
        elif choice == '2':
            left = int(input("Enter left: "))
            top = int(input("Enter top: "))
            right = int(input("Enter right: "))
            bottom = int(input("Enter bottom: "))
            img = crop_image(img, (left, top, right, bottom))
        elif choice == '3':
            width = int(input("Enter new width: "))
            height = int(input("Enter new height: "))
            img = resize_image(img, (width, height))
        elif choice == '4':
            angle = int(input("Enter angle to rotate: "))
            img = rotate_image(img, angle)
        elif choice == '5':
            img = swap_color_channels(img)
        elif choice == '6':
            display_histogram(img)
        elif choice == '7':
            save_path = input("Enter the path to save the image: ")
            img.save(save_path)
            print(f"Image saved to {save_path}")
        elif choice == '0':
            print("Exiting Photoshop operations.")
            break
        else:
            print("Invalid choice. Please try again.")

# Load and display image
def load_image(image_path):
    try:
        img = Image.open(image_path)
        img.show()
        return img
    except Exception as e:
        print(f"Error loading image: {e}")
        return None

# Image processing operations
def invert_colors(img):
    inverted_img = ImageOps.invert(img.convert("RGB"))
    inverted_img.show()
    return inverted_img

def crop_image(img, crop_box):
    cropped_img = img.crop(crop_box)
    cropped_img.show()
    return cropped_img

def resize_image(img, new_size):
    resized_img = img.resize(new_size)
    resized_img.show()
    return resized_img

def rotate_image(img, angle):
    rotated_img = img.rotate(angle)
    rotated_img.show()
    return rotated_img

def swap_color_channels(img):
    np_img = np.array(img)
    swapped_img = np_img[..., ::-1]  # Reverse the order of channels
    swapped_img = Image.fromarray(swapped_img)
    swapped_img.show()
    return swapped_img

def display_histogram(img):
    np_img = np.array(img)
    color = ('r', 'g', 'b')
    plt.figure(figsize=(10, 6))

    for i, col in enumerate(color):
        histogram, bins = np.histogram(np_img[..., i], bins=256, range=(0, 255))
        plt.plot(bins[:-1], histogram, color=col)

    plt.title('Color Histogram')
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')
    plt.legend(color)
    plt.show()

# Main function to ask for user selection
def main():
    print("Choose an option:")
    print("1. Tabular Data Processing")
    print("2. Photoshop Operations")

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == '1':
        file_path = input("Please enter the path to the CSV file: ").strip()
        try:
            df = pd.read_csv(file_path)
            print(f"Data loaded successfully from {file_path}")
            df = tabular_data_processing(df)  # Call the tabular data processing function
        except Exception as e:
            print(f"Error loading CSV file: {e}")
    elif choice == '2':
        image_path = input("Please enter the path to the image file (jpg, png): ").strip()
        try:
            img = load_image(image_path)
            if img:
                photoshop_operations()  # Call the photoshop operations function
        except Exception as e:
            print(f"Error loading image: {e}")
    else:
        print("Invalid choice. Please choose 1 or 2.")

# Run the main function
if __name__ == "__main__":
    main()


ModuleNotFoundError: No module named 'PIL'