In [2]:
print("hello, lets begin numpy with Array foundamentals")


hello, lets begin numpy with Array foundamentals


In [3]:
import numpy as np


Creating arrays from lists or functions

Understanding shape, dtype, ndim

Array attributes (size, itemsize)

Reshape, flatten, transpose

Type conversion (astype)

Element-wise operations (add, sub, mul, div)

arange, linspace, zeros, ones, full, eye



In [5]:
myarray = np.random.choice([1, 2, 3, 4, 5])

In [6]:
myarray


np.int64(2)

In [7]:
a=[1,2,3,4,5,6,7,8,9,10]


In [8]:
type(a)

list

In [9]:
x=np.array(a)

In [11]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(x)

numpy.ndarray

In [14]:
c=np.array([a,x])

In [15]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [17]:
c=np.array([1,2,3,4],dtype=np.float32)

In [18]:
c

array([1., 2., 3., 4.], dtype=float32)

Arrays of zero and ones

In [19]:
x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

Random numbers in ndarrays 

In [23]:
random_array=np.random.rand(2,5)

In [24]:

random_array


array([[0.51229291, 0.3601981 , 0.20567987, 0.86437083, 0.54463374],
       [0.47634741, 0.71524707, 0.58182145, 0.23544409, 0.83237799]])

In [25]:
print(random_array)

[[0.51229291 0.3601981  0.20567987 0.86437083 0.54463374]
 [0.47634741 0.71524707 0.58182145 0.23544409 0.83237799]]


In [26]:
p=np.random.randint(1,100, size=(4,4))

In [27]:
p

array([[78, 91, 63,  2],
       [27, 69, 59, 90],
       [30, 20, 38, 65],
       [22, 87, 96, 11]], dtype=int32)

NameError: name 'P' is not defined