Array Basic Functions 

In [2]:
import numpy as np

1D,2D,3D Array creations

In [3]:
arr1=np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [45]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Special Arrays

In [10]:
zero_mat=np.zeros((3,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
ones_mat=np.ones((3,3))
print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
empty_mat=np.empty((2,2))
print(empty_mat)

[[0.00000000e+000 1.28867842e-311]
 [1.28867842e-311 1.28867842e-311]]


In [24]:
identity_mat=np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Range And Sequence

In [26]:
range_arr=np.arange(10)
print(range_arr)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
range_arr2=np.arange(2,100,3)
print(range_arr2)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71
 74 77 80 83 86 89 92 95 98]


In [29]:
linspace_arr=np.linspace(0,1,4)
print(linspace_arr)

[0.         0.33333333 0.66666667 1.        ]


In [35]:
lin_another=np.linspace(0,1,5)
print(lin_another)

[0.   0.25 0.5  0.75 1.  ]


In [37]:
random_array=np.random.rand(3,3)
print(random_array)

[[0.58169776 0.58525597 0.71125771]
 [0.71645974 0.20594065 0.23268196]
 [0.05580527 0.1292497  0.09526271]]


Array Attributes

In [40]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.dtype)
print(arr3.T)

(3, 3)
2
9
int64
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [52]:
marray=np.array(
[[[1, 2, 3],[4, 5, 6],[7, 8, 9]],
    [[10, 11, 12],[13, 14, 15],[16, 17, 18]],
    [[19, 20, 21],[22, 23, 24],[25, 26, 27]]
 ]
)

In [57]:
print(marray)
print(marray.shape)
print(marray.ndim)
print(marray.size)
print(marray.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
3
27
int64


In [58]:
mul_array=np.array([[1,2,4],[3,4,6]],dtype=np.float32)

In [59]:
mul_array[0,2]

np.float32(4.0)

In [60]:
mul_array.ndim

2

Slicing ,            Basic slice [start:stop:step]

In [65]:
mainArray=np.array([1,2,3,4,5,6,7,8,9,10])


In [71]:

mainArray[:3]


array([1, 2, 3])

In [72]:
mainArray[3:6]

array([4, 5, 6])

In [75]:
mainArray[1:10:2]

array([ 2,  4,  6,  8, 10])

In [ ]:
print(mainArray[1:7])        #  (index 1 to 6)
print(mainArray[::2])        #  (every 2nd element)
print(mainArray[5:])         #  (from index 5 to end)
print(mainArray[:5])         #  (start to index 4)
print(mainArray[::-1])       #   (reverse array)

[2 3 4 5 6 7]
[1 3 5 7 9]
[ 6  7  8  9 10]
[1 2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
